const useBossZhipinJobs = [
  {
    id: '109u94kx',
    name: '技术',
    children: [
      {
        id: '1kqio669',
        name: '后端开发',
        children: [
          {id: '2afb2ryp', name: 'Java'},
          {id: '4g0xpoj0', name: 'C++'},
          {id: '2hwm44m0', name: 'PHP'},
          {id: '8z24ldpb', name: 'C'},
          {id: '71396tn1', name: 'C#'},
          {id: '9of5bhv8', name: '.NET'},
          {id: '2how12c5', name: 'Hadoop'},
          {id: 'n4hegtq6', name: 'Python'},
          {id: '7yj3tntk', name: 'Delphi'},
          {id: '4prc96xk', name: 'VB'},
          {id: '1pof14ob', name: 'Perl'},
          {id: '21zjea5m', name: 'Ruby'},
          {id: 'zd6h4cmg', name: 'Node.js'},
          {id: '1xyh1ve5', name: 'Golang'},
          {id: '11fff39h', name: 'Erlang'},
          {id: '1ia1ulcp', name: '语音/视频/图形开发'},
          {id: 'bkffdro4', name: '数据采集'},
          {id: '1nl3odnx', name: '全栈工程师'},
          {id: '2ghwvlhp', name: 'GIS工程师'},
          {id: 'nu470wg5', name: '后端开发'},
        ],
      },
      {
        id: '1sqay3k5',
        name: '移动开发',
        children: [
          {id: '1ikxjq5f', name: 'HTML5'},
          {id: 'vcm9g2pv', name: 'Android'},
          {id: '2kxcwfk1', name: 'iOS'},
          {id: '53sb8dky', name: '移动web前端'},
          {id: '1pxda2zg', name: 'Flash开发'},
          {id: '1nmta6kg', name: 'JavaScript'},
          {id: '2qb326hu', name: 'U3D'},
          {id: '6yefzmzv', name: 'Cocos2DX'},
          {id: '1prxiily', name: 'UE4'},
          {id: '2n5e06h0', name: '移动开发'},
        ],
      },
      {
        id: '6ifrilpa',
        name: '测试',
        children: [
          {id: '777w42z7', name: '测试工程师'},
          {id: 'qzosfbpv', name: '自动化测试'},
          {id: '2eza87kk', name: '功能测试'},
          {id: '15mhrfx4', name: '性能测试'},
          {id: '1jd087aq', name: '测试开发'},
          {id: '7x5wo92g', name: '移动端测试'},
          {id: 'qy65pwv0', name: '游戏测试'},
          {id: '1mytg35h', name: '硬件测试'},
          {id: '28msqo3i', name: '软件测试'},
          {id: '8802xv7z', name: '渗透测试'},
        ],
      },
      {
        id: '16kdccrt',
        name: '运维/技术支持',
        children: [
          {id: 'c39zegkp', name: '运维工程师'},
          {id: '1hhjnh4x', name: '运维开发工程师'},
          {id: '1s1m9lcs', name: '网络工程师'},
          {id: '7kc50jjy', name: '系统工程师'},
          {id: 'izadi3an', name: 'IT技术支持'},
          {id: 'x62yzon4', name: '系统管理员'},
          {id: '2ltjz9yw', name: '网络安全'},
          {id: '1vlm6c65', name: '系统安全'},
          {id: '1qy7c31i', name: 'DBA'},
        ],
      },
      {
        id: '2j0hhfka',
        name: '数据',
        children: [
          {id: '2i87ww8a', name: '数据'},
          {id: '2p82ymn8', name: 'ETL工程师'},
          {id: '1us5eii9', name: '数据仓库'},
          {id: 'jz5bf637', name: '数据开发'},
          {id: '11tcrudu', name: '数据挖掘'},
          {id: '14qw7ule', name: '数据分析师'},
          {id: '6gkj5hlr', name: '数据架构师'},
        ],
      },
      {
        id: 'qh3j8wd5',
        name: '项目管理',
        children: [
          {id: '1lo23gos', name: '项目经理/主管'},
          {id: '1c02jyv6', name: '项目助理'},
          {id: '1x6x57ux', name: '项目专员'},
          {id: '1vvbodus', name: '实施顾问'},
          {id: '8czjs03h', name: '实施工程师'},
          {id: '732ahbr3', name: '需求分析工程师'},
          {id: '15f7c9hw', name: '硬件项目经理'},
        ],
      },
      {
        id: '25cww2kh',
        name: '硬件开发',
        children: [
          {id: 'krkyrxpf', name: '硬件工程师'},
          {id: '1ko9hslb', name: '嵌入式'},
          {id: '2jka5fbi', name: '自动化'},
          {id: '2dj4taax', name: '单片机'},
          {id: '24l3q45o', name: '电路设计'},
          {id: '1xnormlx', name: '驱动开发'},
          {id: '1s98qqjg', name: '系统集成'},
          {id: '1dt2i10c', name: 'FPGA开发'},
          {id: '2g7f4dvh', name: 'DSP开发'},
          {id: '23ctm6my', name: 'ARM开发'},
          {id: '6pfrc9ym', name: 'PCB工艺'},
          {id: '1is892sk', name: '射频工程师'},
        ],
      },
      {
        id: '1fvwx3v9',
        name: '前端开发',
        children: [
          {id: '2189vjlm', name: '前端开发'},
          {id: '1p261qsj', name: 'Web前端'},
          {id: '2gpiyvsn', name: 'JavaScript'},
          {id: '13pyuuee', name: 'Flash开发'},
          {id: 'xiu6c0uj', name: 'HTML5'},
        ],
      },
      {
        id: '2o6yv3h0',
        name: '通信',
        children: [
          {id: '3zn4xuh2', name: '通信技术工程师'},
          {id: '2mxh98he', name: '通信研发工程师'},
          {id: '1fbeow9l', name: '数据通信工程师'},
          {id: '16oi729f', name: '移动通信工程师'},
          {id: '11hb7n3i', name: '电信网络工程师'},
          {id: '7x4sjc8q', name: '电信交换工程师'},
          {id: 'a99hvb59', name: '有线传输工程师'},
          {id: 'r5bv2qow', name: '无线/射频通信工程师'},
          {id: '106zgbob', name: '通信电源工程师'},
          {id: '25dklq9t', name: '通信标准化工程师'},
          {id: '2p20xn5q', name: '通信项目专员'},
          {id: '5t5utmej', name: '通信项目经理'},
          {id: 'd2o1xgs1', name: '核心网工程师'},
          {id: '25dpeh3a', name: '通信测试工程师'},
          {id: '1na7mc7z', name: '通信设备工程师'},
          {id: '1zurhq3j', name: '光通信工程师'},
          {id: '1p9b6uij', name: '光传输工程师'},
          {id: '1yt3bd9r', name: '光网络工程师'},
        ],
      },
      {
        id: '8qt9r9rs',
        name: '电子/半导体',
        children: [
          {id: '1na31bjw', name: '电气工程师'},
          {id: '1tu1c9vz', name: '电气设计工程师'},
          {id: '4yn19njr', name: '电子工程师'},
          {id: '1pmszrfv', name: '集成电路IC设计'},
          {id: '2jwch07u', name: 'FAE'},
          {id: '1xe420ar', name: 'IC验证工程师'},
        ],
      },
      {
        id: '1q9dwvci',
        name: '高端技术职位',
        children: [
          {id: 'cwmblcfg', name: '高端技术职位'},
          {id: '20v6qiuo', name: '技术经理'},
          {id: 'vzdwmktt', name: '技术总监'},
          {id: 'wercur8t', name: '测试经理'},
          {id: '2np2afyq', name: '架构师'},
          {id: '1tgnmjwd', name: 'CTO'},
          {id: 'dibtoi4i', name: '运维总监'},
          {id: '2uyzx98i', name: '技术合伙人'},
        ],
      },
      {
        id: '2e12fh0u',
        name: '人工智能',
        children: [
          {id: '26gvn49j', name: '人工智能'},
          {id: 'dak8xev5', name: '数据挖掘'},
          {id: '1c8fqh5q', name: '搜索算法'},
          {id: '22m2rstl', name: '自然语言处理'},
          {id: '20ezmlkb', name: '推荐算法'},
          {id: '3wm7c7nh', name: '算法工程师'},
          {id: '84l2niem', name: '智能驾驶系统工程师'},
          {id: '2bzwr614', name: '反欺诈/风控算法'},
          {id: '192iqgao', name: '机器学习'},
          {id: 'wus9q3vf', name: '深度学习'},
          {id: '7r8ljxdy', name: '语音识别'},
          {id: '382ns34i', name: '图像识别'},
          {id: '1tkwjktn', name: '算法研究员'},
        ],
      },
      {
        id: '2t3cbkqp',
        name: '销售技术支持',
        children: [
          {id: '2fpih58i', name: '销售技术支持'},
          {id: '1iyhk7d1', name: '售前技术支持'},
          {id: '4xougifz', name: '售后技术支持'},
        ],
      },
      {
        id: '20w3780b',
        name: '其他技术职位',
        children: [{id: '2e2le2dm', name: '其他技术职位'}],
      },
    ],
  },
  {
    id: '9dfwjt9l',
    name: '产品',
    children: [
      {
        id: 'bk9ua2f7',
        name: '产品经理',
        children: [
          {id: '1rx0o4pg', name: '产品经理'},
          {id: '5jaq46u0', name: '网页产品经理'},
          {id: '27iucoa4', name: '移动产品经理'},
          {id: '9botn7iz', name: '产品助理'},
          {id: 'u2fmerxc', name: '数据产品经理'},
          {id: '288e7prn', name: '电商产品经理'},
          {id: 'dks2trca', name: '游戏策划'},
          {id: '28uss055', name: '电商产品开发'},
          {id: '1pp6hkid', name: '硬件产品经理'},
        ],
      },
      {
        id: '2pu6lg4v',
        name: '高端产品职位',
        children: [
          {id: '1ux6cifc', name: '高端产品职位'},
          {id: '1dwiweua', name: '产品总监/VP'},
          {id: 'p0h83fk6', name: '游戏制作人'},
        ],
      },
      {
        id: '65cg2yn6',
        name: '其他产品职位',
        children: [{id: '1y5hlhzf', name: '其他产品职位'}],
      },
    ],
  },
  {
    id: '232ezfmz',
    name: '设计',
    children: [
      {
        id: 'dh94ijhr',
        name: '视觉/交互设计',
        children: [
          {id: '4y4am9vu', name: '视觉设计'},
          {id: '4o0vi0o2', name: '视觉设计师'},
          {id: '1mf9ib2t', name: '网页设计师'},
          {id: '2a5672ti', name: 'Flash设计师'},
          {id: '21snpddo', name: 'APP设计师'},
          {id: '1i0d85u1', name: 'UI设计师'},
          {id: '21zc7jg7', name: '平面设计'},
          {id: '1iijpmj9', name: '3D设计师'},
          {id: 'avsj45mo', name: '广告设计'},
          {id: '2lvwycok', name: '多媒体设计师'},
          {id: '5bdku7vi', name: '原画师'},
          {id: '1e70jt98', name: 'CAD设计/制图'},
          {id: '4lgwlm4o', name: '美工'},
          {id: '2g0i5405', name: '包装设计'},
          {id: '18ale92o', name: '设计师助理'},
          {id: '2qwomv3i', name: '动画设计'},
          {id: '4zqo3xnj', name: '插画师'},
          {id: '115kgmmy', name: '漫画师'},
          {id: '2ogx03kw', name: '人像修图师'},
          {id: '6fsxn23i', name: '交互设计师'},
        ],
      },
      {
        id: 'b6iu0xja',
        name: '游戏设计',
        children: [
          {id: 'cwm8csnk', name: '游戏特效'},
          {id: 'g86v9m82', name: '游戏界面设计师'},
          {id: 'b3z9razu', name: '游戏场景'},
          {id: '2kucebk8', name: '游戏角色'},
          {id: '2au5xxhz', name: '游戏动作'},
          {id: '2gdhbtic', name: '游戏数值策划'},
        ],
      },
      {
        id: '9nibektd',
        name: '用户研究',
        children: [
          {id: '3emrpckv', name: '数据分析师'},
          {id: '8mxts9dy', name: '用户研究员'},
          {id: 'c3bjj42v', name: 'UX设计师'},
          {id: '6i623h6q', name: '用户研究经理'},
          {id: 'e63iq3uv', name: '用户研究总监'},
        ],
      },
      {
        id: '1jl4a2i8',
        name: '高端设计职位',
        children: [
          {id: '25gqqb16', name: '高端设计职位'},
          {id: '3o85vq07', name: '设计经理/主管'},
          {id: '2g8kvruy', name: '设计总监'},
          {id: 'y0cfntbc', name: '视觉设计总监'},
        ],
      },
      {
        id: 'w29asmal',
        name: '非视觉设计',
        children: [
          {id: '2g3qygp2', name: '非视觉设计'},
          {id: '2mp4xzwu', name: '展览/展示设计'},
          {id: 'bpxfh8su', name: '照明设计'},
          {id: '1be8f8mx', name: '服装/纺织设计'},
          {id: '4ttudita', name: '工业设计'},
          {id: '6ax61opf', name: '橱柜设计'},
          {id: '2p5hnves', name: '家具设计'},
          {id: '5kwdvfpu', name: '家居设计'},
          {id: '1qq2xc9y', name: '珠宝设计'},
          {id: '296qi1zb', name: '室内设计'},
          {id: 'qdgfvf6o', name: '陈列设计'},
        ],
      },
      {
        id: '2vcys91h',
        name: '其他设计职位',
        children: [{id: '1k8ybwz7', name: '其他设计职位'}],
      },
    ],
  },
  {
    id: '22qsb9xx',
    name: '运营',
    children: [
      {
        id: '2g7pwudm',
        name: '运营',
        children: [
          {id: '1jh8ofp2', name: '运营'},
          {id: 'caurzqzt', name: '用户运营'},
          {id: '2ol9xbz1', name: '产品运营'},
          {id: '6n60l1vv', name: '数据/策略运营'},
          {id: 'aulybkc5', name: '内容运营'},
          {id: '1mnu4hvo', name: '活动运营'},
          {id: '2pgo57vn', name: '商家运营'},
          {id: '5ap3xnt1', name: '品类运营'},
          {id: '18fehurj', name: '游戏运营'},
          {id: '2q5xmqnu', name: '网站运营'},
          {id: 'b3lklivj', name: '新媒体运营'},
          {id: '38vn4uwh', name: '社区运营'},
          {id: '288ca80x', name: '微信运营'},
          {id: '2mu94luk', name: '线下拓展运营'},
          {id: 'c47to9b4', name: '国内电商运营'},
          {id: '2gt1d2qz', name: '运营助理/专员'},
          {id: '1pgum9ry', name: '内容审核'},
          {id: '20rohwfm', name: '数据标注/AI训练师'},
          {id: '1h5s8lid', name: '直播运营'},
          {id: '27vnetfo', name: '车辆运营'},
          {id: '75fjj2cu', name: '跨境电商运营'},
          {id: '1pv1mhw8', name: '视频运营'},
        ],
      },
      {
        id: '2bijz6vl',
        name: '编辑',
        children: [
          {id: '16romoe2', name: '编辑'},
          {id: '1yotp031', name: '主编/副主编'},
          {id: '9qgqahwi', name: '文案编辑'},
          {id: '6revtchy', name: '网站编辑'},
          {id: '55bylj5t', name: '采编'},
          {id: '16mgmcal', name: '医学编辑'},
        ],
      },
      {
        id: '13cwvwj1',
        name: '客服',
        children: [
          {id: 'wadd1nfa', name: '售前客服'},
          {id: '4v9jd7y9', name: '售后客服'},
          {id: '2moylbmi', name: '网络客服'},
          {id: '5ip2jm0r', name: '客服经理'},
          {id: '46zukwk5', name: '客服专员'},
          {id: 'xjysmq1f', name: '客服主管'},
          {id: 's16utf7k', name: '电话客服'},
          {id: '1omg6qgl', name: '咨询热线/呼叫中心客服'},
        ],
      },
      {
        id: 'ctaqgmvw',
        name: '高端运营职位',
        children: [
          {id: '85swdv6a', name: '高端运营职位'},
          {id: '2j8821vt', name: '运营总监'},
          {id: '2nt11fr7', name: 'COO'},
          {id: '23ghzp2j', name: '客服总监'},
          {id: '28v7p36z', name: '运营经理/主管'},
        ],
      },
      {
        id: '193f5vju',
        name: '其他运营职位',
        children: [{id: '9iw3tgtt', name: '其他运营职位'}],
      },
    ],
  },
  {
    id: '2e7d3irw',
    name: '市场',
    children: [
      {
        id: '1a64kat2',
        name: '政府事务',
        children: [
          {id: 'g3vifl1s', name: '政府关系'},
          {id: '2c5zg4z5', name: '政策研究'},
          {id: '1zefrd7u', name: '企业党建'},
        ],
      },
      {
        id: '6b5mxi8d',
        name: '市场/营销',
        children: [
          {id: '20wupf40', name: '网络推广'},
          {id: 'nk4gvv8i', name: '市场营销'},
          {id: '2s182zaz', name: '市场策划'},
          {id: '1jdowloh', name: '市场顾问'},
          {id: 'whr0w6vj', name: '市场推广'},
          {id: '29dpy6tk', name: 'SEO'},
          {id: '3orqtjp1', name: 'SEM'},
          {id: '2fy76d3h', name: '商务渠道'},
          {id: '741m08gu', name: '商业数据分析'},
          {id: '1ft1pgys', name: '活动策划'},
          {id: '3h5k1k48', name: '网络营销'},
          {id: '63ybs64h', name: '海外市场'},
          {id: '581htlt5', name: 'APP推广'},
          {id: '2p63ityp', name: '选址开发'},
          {id: '3hzt7en1', name: '游戏推广'},
          {id: '27wg0em4', name: '营销主管'},
        ],
      },
      {
        id: '2dqvfxsi',
        name: '公关媒介',
        children: [
          {id: '16c9byde', name: '公关媒介'},
          {id: '1zeqf5e0', name: '媒介经理'},
          {id: '223z402s', name: '广告协调'},
          {id: '3z596zqm', name: '品牌公关'},
          {id: '5i98xhqy', name: '媒介专员'},
          {id: '1r9mdbm6', name: '活动策划执行'},
          {id: '14pqezpk', name: '媒介策划'},
        ],
      },
      {
        id: '1v57zmmc',
        name: '会务会展',
        children: [
          {id: '1lickq7d', name: '会务会展'},
          {id: '205gymk8', name: '会议活动策划'},
          {id: '4hbwkfl1', name: '会议活动执行'},
          {id: '2qe5rutl', name: '会展活动策划'},
          {id: '2k7plvqh', name: '会展活动执行'},
        ],
      },
      {
        id: '1pdu0kwd',
        name: '广告',
        children: [
          {id: '8eeymldu', name: '广告'},
          {id: '1knjs5nc', name: '广告/会展项目经理'},
          {id: '2l8wjus8', name: '广告创意设计'},
          {id: '1ww70ilv', name: '美术指导'},
          {id: '1ytggrq7', name: '广告设计'},
          {id: '1ctkev7l', name: '策划经理'},
          {id: '24pputcc', name: '广告文案'},
          {id: '2mklp7ri', name: '广告制作'},
          {id: '2oyfdxp3', name: '媒介投放'},
          {id: '1rp9xcb0', name: '媒介合作'},
          {id: '1niun94l', name: '广告审核'},
        ],
      },
      {
        id: '2ph2orna',
        name: '高端市场职位',
        children: [
          {id: '18p0hpye', name: '高端市场职位'},
          {id: '2gpx1ihf', name: '市场总监'},
          {id: '1mm6epjf', name: 'CMO'},
          {id: 'af2l917c', name: '公关总监'},
          {id: 'gn7ul6uz', name: '媒介总监'},
          {id: '5jkv6868', name: '创意总监'},
        ],
      },
      {
        id: '93h56qni',
        name: '其他市场职位',
        children: [{id: '2ei1qpnx', name: '其他市场职位'}],
      },
    ],
  },
  {
    id: 'd7j7gghk',
    name: '人事/财务/行政',
    children: [
      {
        id: '6iaizzn7',
        name: '人力资源',
        children: [
          {id: '9qja291p', name: '招聘'},
          {id: 'yo5crfih', name: 'HRBP'},
          {id: '1g8b85wd', name: '人力资源专员/助理'},
          {id: '3rumv7j9', name: '培训'},
          {id: '27rr77c1', name: '薪资福利'},
          {id: 'ababe62g', name: '绩效考核'},
          {id: '589lpsjo', name: '人力资源经理/主管'},
          {id: '5fpxm8ry', name: '人力资源VP/CHO'},
          {id: '7ie9w09w', name: '人力资源总监'},
          {id: 'h7b6pfxr', name: '员工关系'},
          {id: '5ypzv1rd', name: '组织发展'},
        ],
      },
      {
        id: '1e50vcs8',
        name: '行政',
        children: [
          {id: '22tkr9mc', name: '行政专员/助理'},
          {id: '1q2dyi0t', name: '前台'},
          {id: 'gym45mle', name: '经理助理'},
          {id: '454ar1j8', name: '后勤'},
          {id: '1zzj0x8n', name: '行政经理/主管'},
          {id: '23jqlsip', name: '行政总监'},
        ],
      },
      {
        id: '7vywelv0',
        name: '财务',
        children: [
          {id: '5txp05f3', name: '财务'},
          {id: '25zz0ibe', name: '会计'},
          {id: '4lmmqa3x', name: '出纳'},
          {id: '1j3evni1', name: '财务顾问'},
          {id: '1ucg37c5', name: '结算会计'},
          {id: '7jnj3778', name: '税务'},
          {id: '6j798sbu', name: '审计'},
          {id: 'cd9qaqeo', name: '成本会计'},
          {id: '1wmccmhe', name: '总账会计'},
          {id: '1kaaqixu', name: '财务经理/主管'},
          {id: 'oywynw76', name: 'CFO'},
          {id: '9yfhyppt', name: '财务总监/VP'},
        ],
      },
      {
        id: '1uffnezk',
        name: '法务',
        children: [
          {id: '6rifpcdr', name: '法务专员/助理'},
          {id: '1yhv6lnp', name: '律师'},
          {id: '7hxcgdxl', name: '法律顾问'},
          {id: '1vjogjtk', name: '法务经理/主管'},
          {id: '378imt9f', name: '法务总监'},
        ],
      },
      {
        id: 'yl84j61h',
        name: '其他职能职位',
        children: [{id: 'lds1mvi3', name: '其他职能职位'}],
      },
    ],
  },
  {
    id: '194zppij',
    name: '高级管理',
    children: [
      {
        id: '1pmt87nj',
        name: '高级管理职位',
        children: [
          {id: '22t6x4q1', name: '高级管理职位'},
          {id: '9bslyx40', name: '总裁/总经理/CEO'},
          {id: '2ix2u7wg', name: '副总裁/副总经理/VP'},
          {id: '1l50iags', name: '分公司/代表处负责人'},
          {id: 'hgdpx147', name: '区域负责人(辖多个分公司)'},
          {id: 'x7b4wgc4', name: '总助/CEO助理/董事长助理'},
          {id: 'l6bwf041', name: '联合创始人'},
          {id: 'cprjvv9q', name: '董事会秘书'},
        ],
      },
    ],
  },
  {
    id: '1wrk1907',
    name: '销售',
    children: [
      {
        id: 'xx1osptd',
        name: '销售行政/商务',
        children: [
          {id: '2fecn73s', name: '商务专员'},
          {id: '2p0xl76a', name: '商务经理'},
          {id: '1zvhe7vy', name: '销售助理'},
          {id: '5rkzk2re', name: '商务总监'},
          {id: '2prqaafm', name: '销售运营'},
        ],
      },
      {
        id: '10fc472w',
        name: '房地产销售/招商',
        children: [
          {id: '16hlrl3v', name: '置业顾问'},
          {id: 'd2su3jrf', name: '地产中介'},
          {id: '1rxgy46o', name: '房地产销售/招商'},
          {id: '20gydpyz', name: '物业招商管理'},
          {id: '7nipkqug', name: '房地产销售总监'},
        ],
      },
      {
        id: '1on5bukj',
        name: '服务业销售',
        children: [
          {id: '3htcplwm', name: '服装销售'},
          {id: '1lkfoduw', name: '彩妆顾问'},
          {id: '267u9368', name: '美容顾问'},
          {id: '23wnqxm4', name: '会籍顾问'},
          {id: '4b4m23w5', name: '珠宝销售'},
          {id: 'm4outiei', name: '旅游顾问'},
          {id: 'b8tyx6sp', name: '瘦身顾问'},
        ],
      },
      {
        id: '7sa7kis2',
        name: '汽车销售',
        children: [
          {id: '3hevgx9e', name: '汽车销售'},
          {id: '6qgkmd1o', name: '汽车配件销售'},
        ],
      },
      {
        id: '26m891az',
        name: '广告/会展销售',
        children: [
          {id: '1obfuwtb', name: '广告销售'},
          {id: '4q14pm7r', name: '会议活动销售'},
          {id: '1d7fa11i', name: '会展活动销售'},
          {id: '7jzobl5w', name: '媒介顾问'},
        ],
      },
      {
        id: '109ssjy9',
        name: '金融销售',
        children: [
          {id: '2jre0c9x', name: '证券经纪人'},
          {id: '2mq60qol', name: '信用卡销售'},
          {id: '1pp1iwdu', name: '保险顾问'},
          {id: '1er2m89y', name: '理财顾问'},
        ],
      },
      {
        id: 'csfarl3u',
        name: '外贸销售',
        children: [
          {id: '5w2fvpvv', name: '外贸经理'},
          {id: '1mr80us9', name: '外贸业务员'},
        ],
      },
      {
        id: '4b5wai2p',
        name: '销售',
        children: [
          {id: '2pz4kxy7', name: '销售'},
          {id: '6bbw97md', name: '销售专员'},
          {id: 'mcs9e627', name: '客户代表'},
          {id: '2eabyucv', name: '大客户代表'},
          {id: 'cxp7ffnz', name: 'BD经理'},
          {id: '137hoi39', name: '渠道销售'},
          {id: '22tkfnv7', name: '代理商销售'},
          {id: '1cfsppg1', name: '电话销售'},
          {id: 'cyiway35', name: '销售顾问'},
          {id: '1h47ka26', name: '网络销售'},
          {id: '9a0tora7', name: '销售工程师'},
          {id: '1ebecsyl', name: '客户经理'},
        ],
      },
      {
        id: '1hu44q8q',
        name: '课程销售',
        children: [
          {id: '2ls6p6ci', name: '课程顾问'},
          {id: '1vctzzz7', name: '招生顾问'},
          {id: '3e7znm7d', name: '留学顾问'},
        ],
      },
      {
        id: '1nst6tjo',
        name: '医疗销售',
        children: [
          {id: '5ih4yas0', name: '医疗销售'},
          {id: 'c0oei87p', name: '医疗器械销售'},
          {id: 'cbnbpflh', name: '医药代表'},
          {id: '6hsmm1ab', name: '健康顾问'},
          {id: '1f3i5jyu', name: '医美咨询'},
        ],
      },
      {
        id: 'tc09cbu5',
        name: '销售管理',
        children: [
          {id: 'c2sniihd', name: '销售管理'},
          {id: 'eljlkeew', name: '销售经理'},
          {id: '9499gqh8', name: '销售总监'},
          {id: '1yy61swz', name: '区域总监'},
          {id: '4o5j68iy', name: '城市经理'},
          {id: '21w5mbxc', name: '销售VP'},
          {id: 'vbezfaqk', name: '团队经理'},
        ],
      },
      {
        id: '2h7rpa1n',
        name: '其他销售职位',
        children: [{id: '9181k2ir', name: '其他销售职位'}],
      },
    ],
  },
  {
    id: 'cr6ys9ua',
    name: '传媒',
    children: [
      {
        id: 'xo1vqyfc',
        name: '采编/写作/出版',
        children: [
          {id: '4tqpa018', name: '采编/写作/出版'},
          {id: '2puqgmkq', name: '印刷排版'},
          {id: '201xb1vc', name: '记者/采编'},
          {id: 'cdm9z0fi', name: '编辑'},
          {id: '20qkh1du', name: '作者/撰稿人'},
          {id: 'mii0ycwu', name: '出版发行'},
          {id: 'phhw053y', name: '校对录入'},
        ],
      },
      {
        id: '2kd7pkt2',
        name: '公关媒介',
        children: [
          {id: '241r0cxi', name: '公关媒介'},
          {id: '1yy7p00g', name: '媒介经理'},
          {id: '68hprcb7', name: '媒介专员'},
          {id: '2v5nocig', name: '广告协调'},
          {id: '5qcjh60f', name: '品牌公关'},
          {id: '5kkcuk26', name: '活动策划执行'},
          {id: 'usrb49q0', name: '媒介策划'},
        ],
      },
      {
        id: '3bpjjrdr',
        name: '广告',
        children: [
          {id: '273yff92', name: '广告'},
          {id: '2gs4f6id', name: '广告/会展项目经理'},
          {id: '242dusb0', name: '广告创意设计'},
          {id: '2kpb1685', name: '美术指导'},
          {id: '1uretixs', name: '广告设计'},
          {id: 'mog25lx3', name: '策划经理'},
          {id: '2kbdiyz8', name: '广告文案'},
          {id: '6fxi9b7f', name: '广告制作'},
          {id: 'c7gsbx51', name: '媒介投放'},
          {id: '1tljdfyj', name: '媒介合作'},
          {id: '88v5mrpv', name: '广告审核'},
        ],
      },
      {
        id: '1jlsk10s',
        name: '影视媒体',
        children: [
          {id: 'ssorjfrj', name: '带货主播'},
          {id: '5cd84qbi', name: '影视媒体'},
          {id: '28r15hsi', name: '艺人助理'},
          {id: '14pb8h69', name: '主持人/DJ'},
          {id: '671fzruo', name: '主播助理'},
          {id: 'woysl1zg', name: '灯光师'},
          {id: '27d2giai', name: '剪辑师'},
          {id: 'csdu0juw', name: '影视特效'},
          {id: '1slp6t1j', name: '导演/编导'},
          {id: '6v2irfny', name: '摄影/摄像'},
          {id: 'd9svd4s9', name: '视频编辑'},
          {id: '6epwg2iy', name: '音频编辑'},
          {id: '10wb1qyo', name: '经纪人'},
          {id: '10k0fdgv', name: '后期制作'},
          {id: '5f9xygck', name: '影视发行'},
          {id: '2krke7vf', name: '影视策划'},
          {id: '1rhziqup', name: '主播'},
          {id: '27u9z9wl', name: '演员/配音/模特'},
          {id: '3cqpg2co', name: '化妆/造型/服装'},
          {id: '21eijq0y', name: '放映员'},
          {id: '24ny3rsi', name: '录音/音效'},
          {id: '2icttzl4', name: '制片人'},
          {id: '28bnjzog', name: '编剧'},
        ],
      },
      {
        id: '4g1i09o9',
        name: '其他传媒职位',
        children: [{id: '444cciws', name: '其他传媒职位'}],
      },
    ],
  },
  {
    id: '2nfvbgn0',
    name: '金融',
    children: [
      {
        id: '35s7zykm',
        name: '证券/基金/期货',
        children: [
          {id: '1q1t2dgp', name: '买方分析师'},
          {id: 'bjrvgajw', name: '股票/期货操盘手'},
          {id: '8vgkn1zg', name: '基金经理'},
          {id: '1w8ykxej', name: '投资银行业务'},
          {id: 'b4usjm3t', name: '证券/基金/期货'},
          {id: '1mk0f12d', name: '卖方分析师'},
          {id: 'd5iqfxpp', name: '证券交易员'},
        ],
      },
      {
        id: '871p7l54',
        name: '投融资',
        children: [
          {id: '9vkdzlyt', name: '投融资'},
          {id: '2lvf5i47', name: '投资经理'},
          {id: '1xl1smzw', name: '行业研究'},
          {id: '103h4oga', name: '资产管理'},
          {id: '1j8vclgo', name: '投资总监'},
          {id: 'gwe5jl3s', name: '投资VP'},
          {id: '2koi8gjb', name: '投资合伙人'},
          {id: '203tehxp', name: '融资'},
          {id: '2u0x9g6d', name: '并购'},
          {id: '7o55qyad', name: '投后管理'},
          {id: 'bke2lvaz', name: '投资助理'},
          {id: '2e6ek5ke', name: '其他投融资职位'},
          {id: '4tjef006', name: '投资顾问'},
        ],
      },
      {
        id: 'dmizz11y',
        name: '银行',
        children: [
          {id: 'ugthndwh', name: '银行'},
          {id: '1ve82d4m', name: '分析师'},
          {id: 'oqsp6g2s', name: '柜员'},
          {id: '1whpj5jm', name: '商务渠道'},
          {id: '13agiwf9', name: '大堂经理'},
          {id: '6c65vmys', name: '客户经理'},
          {id: '9jpsw07m', name: '信贷管理'},
        ],
      },
      {
        id: 'dqmiytm2',
        name: '保险',
        children: [
          {id: '1k41oqw0', name: '保险精算师'},
          {id: '2j63y8ar', name: '保险理赔'},
        ],
      },
      {
        id: 'w3noajcr',
        name: '中后台',
        children: [
          {id: '23vni4mz', name: '风控'},
          {id: '1uu1ow4i', name: '法务'},
          {id: '1eg64scd', name: '资信评估'},
          {id: '3mgni3lx', name: '合规稽查'},
          {id: '29o42hvc', name: '清算'},
        ],
      },
      {
        id: '108btj5j',
        name: '互联网金融',
        children: [
          {id: '50ldudut', name: '互联网金融'},
          {id: '15uyb5f0', name: '金融产品经理'},
          {id: 'rwmjp2yf', name: '催收员'},
          {id: '5x1gkqfy', name: '分析师'},
          {id: '3k3pjx7b', name: '投资经理'},
          {id: '1lywi346', name: '清算'},
        ],
      },
      {
        id: 'bfl0wn1r',
        name: '其他金融职位',
        children: [{id: '2q0z0d3g', name: '其他金融职位'}],
      },
    ],
  },
  {
    id: '1jglpxxo',
    name: '教育培训',
    children: [
      {
        id: '6qcgdpid',
        name: '教育产品研发',
        children: [
          {id: '1aktsz68', name: '教育产品研发'},
          {id: 'k4tgxtsc', name: '课程设计'},
          {id: '2h2kxxhi', name: '课程编辑'},
          {id: 'yn4zmu99', name: '培训研究'},
          {id: '193jg0jf', name: '培训师'},
          {id: 'ddu529ua', name: '培训策划'},
          {id: '2ndwxawn', name: '其他教育产品研发职位'},
        ],
      },
      {
        id: '12gs2shc',
        name: '教育行政',
        children: [
          {id: 'd5nyvgoj', name: '教育行政'},
          {id: '2mhdrccw', name: '园长/副园长'},
          {id: '6y7g91hr', name: '校长/副校长'},
          {id: 'd0klbugc', name: '教务管理'},
          {id: '1safepnu', name: '教学管理'},
          {id: '2oj9ozvc', name: '班主任/辅导员'},
        ],
      },
      {
        id: '9i4ozj8i',
        name: '教师',
        children: [
          {id: 'u2oen376', name: '教师'},
          {id: '2084i4s3', name: '日语教师'},
          {id: '433pc205', name: '其他外语教师'},
          {id: '6yn1kdsl', name: '语文教师'},
          {id: '1u3b4dn2', name: '数学教师'},
          {id: '1mojqkux', name: '物理教师'},
          {id: '1g5qnukj', name: '化学教师'},
          {id: 'r7gc50ee', name: '生物教师'},
          {id: '2fru3qko', name: '家教'},
          {id: '1sjt3ymv', name: '托管老师'},
          {id: '1k3zc5mq', name: '早教老师'},
          {id: '6obxfkol', name: '助教'},
          {id: 'x36tepx0', name: '高中教师'},
          {id: '1wuh0pxc', name: '初中教师'},
          {id: '4g5ry7bw', name: '小学教师'},
          {id: '29zdzy7l', name: '幼教'},
          {id: '72wh7t64', name: '理科教师'},
          {id: '75rgk7x1', name: '文科教师'},
          {id: '5mu9i5y9', name: '英语教师'},
          {id: '1mkh4m70', name: '音乐教师'},
          {id: '1j9xrf83', name: '美术教师'},
          {id: '10grx1b2', name: '体育教师'},
          {id: '9suif1e6', name: '就业老师'},
        ],
      },
      {
        id: '27wo9x6k',
        name: 'IT培训',
        children: [
          {id: '26gplgdr', name: 'IT培训'},
          {id: 'ckm8ncyv', name: 'Java培训讲师'},
          {id: '2pj8s292', name: 'Android培训讲师'},
          {id: 'alhh49jb', name: 'iOS培训讲师'},
          {id: '5medg7k9', name: 'PHP培训讲师'},
          {id: '1rfk2h61', name: '.Net培训讲师'},
          {id: '2erpx12i', name: 'C++培训讲师'},
          {id: 'lwlhnnfw', name: 'Unity 3D培训讲师'},
          {id: '15h0u5mx', name: 'Web前端培训讲师'},
          {id: '87d2gv2a', name: '软件测试培训讲师'},
          {id: '210if6xg', name: '动漫培训讲师'},
          {id: '2ci0z19r', name: 'UI设计培训讲师'},
        ],
      },
      {
        id: '2epqsbu1',
        name: '职业培训',
        children: [
          {id: 'bram7umg', name: '财会培训讲师'},
          {id: '7wi14m11', name: 'HR培训讲师'},
          {id: '20dag9b7', name: '培训师'},
          {id: '1rp0rmh7', name: '拓展培训'},
        ],
      },
      {
        id: '1z33thua',
        name: '特长培训',
        children: [
          {id: '29xbcamr', name: '教练'},
          {id: '8vm2ddep', name: '武术教练'},
          {id: '1pzuyi8n', name: '轮滑教练'},
          {id: '12ysrvjx', name: '表演教师'},
          {id: '1691apcj', name: '机器人教师'},
          {id: '1pne31bi', name: '书法教师'},
          {id: '2inzf6gl', name: '钢琴教师'},
          {id: '2e4z06qu', name: '吉他教师'},
          {id: 't8n3sl8h', name: '古筝教师'},
          {id: '2diehi9t', name: '播音主持教师'},
          {id: '1r9lqb9q', name: '乐高教师'},
          {id: '1ggl0ggd', name: '舞蹈老师'},
          {id: '1k4ude1c', name: '瑜伽老师'},
          {id: '1rnoanjo', name: '游泳教练'},
          {id: '2hjg19jy', name: '健身教练'},
          {id: '2ebcgxj4', name: '篮球/羽毛球教练'},
          {id: 'zgj4iwsi', name: '跆拳道教练'},
        ],
      },
      {
        id: '1u06errv',
        name: '其他教育培训职位',
        children: [{id: '13mkz50m', name: '其他教育培训职位'}],
      },
    ],
  },
  {
    id: '7zx40zgi',
    name: '医疗健康',
    children: [
      {
        id: '1tjvdf59',
        name: '临床试验',
        children: [
          {id: '1eejrena', name: '临床研究'},
          {id: 'cjkrotf4', name: '临床协调'},
          {id: '1kq2amd4', name: '临床数据分析'},
          {id: '1r034dd9', name: '临床项目经理'},
          {id: '1zvbr260', name: '医学总监'},
        ],
      },
      {
        id: '8opj8meo',
        name: '医生/医技',
        children: [
          {id: '22u5hrz4', name: '医生'},
          {id: 'bu4uxk1h', name: '幼儿园保健医'},
          {id: '1vxg5w65', name: '医生助理'},
          {id: '930kcl8e', name: '医学影像/放射科医师'},
          {id: 'yo4e40xz', name: '超声科医生'},
          {id: '1qq1p5mb', name: '内科医生'},
          {id: '4wtdedxg', name: '全科医生'},
          {id: '2tgjkkbo', name: '中医'},
          {id: '23js5aoy', name: '心理医生'},
          {id: '28sbwro3', name: '药剂师'},
          {id: '9q28pg28', name: '口腔科医生'},
          {id: '2dooiv3o', name: '康复治疗师'},
          {id: 'awlinvwx', name: '验光师'},
          {id: 'upm7gib1', name: '检验科医师'},
          {id: 's6nk7o8u', name: '其他医生职位'},
        ],
      },
      {
        id: '78my82gw',
        name: '护士/护理',
        children: [
          {id: '1so0e30y', name: '护士长'},
          {id: 'x6ltiejj', name: '护士'},
          {id: '56mvg6xt', name: '导医'},
        ],
      },
      {
        id: '23ke2dwt',
        name: '健康整形',
        children: [
          {id: '201qarnk', name: '健康整形'},
          {id: '8q5brtso', name: '营养师/健康管理师'},
          {id: 's1xtnf43', name: '整形师'},
          {id: '2h2rrqgs', name: '理疗师'},
          {id: 'udy3es7u', name: '针灸推拿'},
        ],
      },
      {
        id: '694lm16i',
        name: '生物制药',
        children: [
          {id: '2hgt5xn7', name: '生物制药'},
          {id: 'gvpzavq7', name: '药品注册'},
          {id: '109tz43z', name: '药品生产'},
          {id: '5oyxi60q', name: '医药项目经理'},
          {id: '25sr2rr0', name: '医药研发'},
        ],
      },
      {
        id: '286hr1gp',
        name: '医疗器械',
        children: [
          {id: '5uv9ibkm', name: '医疗器械注册'},
          {id: '6rfbg94n', name: '医疗器械生产/质量管理'},
          {id: '2iq2tjhw', name: '医疗器械研发'},
        ],
      },
      {
        id: '2ko40938',
        name: '药店',
        children: [
          {id: '1xk0jepu', name: '药店店长'},
          {id: 'ljsp6xcz', name: '执业药师/驻店药师'},
          {id: '1vlwvuag', name: '药店店员'},
        ],
      },
      {
        id: '23fliyl5',
        name: '其他医疗健康职位',
        children: [{id: '1p6t0o01', name: '其他医疗健康职位'}],
      },
    ],
  },
  {
    id: '2az9zahf',
    name: '采购/贸易',
    children: [
      {
        id: '2hinr1cm',
        name: '采购',
        children: [
          {id: 'uva8s6d9', name: '采购'},
          {id: 'tx5hfsrs', name: '商品经理'},
          {id: '22falh2w', name: '供应商质量工程师'},
          {id: '1b8ur25z', name: '采购总监'},
          {id: '37lh0lnu', name: '采购经理/主管'},
          {id: '1p6dbwoh', name: '采购专员/助理'},
          {id: '2l7b40dq', name: '买手'},
          {id: '20uyn3v4', name: '采购工程师'},
        ],
      },
      {
        id: '1o72pi49',
        name: '进出口贸易',
        children: [
          {id: '1ho9d1u3', name: '进出口贸易'},
          {id: '15jijl2l', name: '贸易跟单'},
          {id: '5z90ycvl', name: '报关/报检员'},
          {id: '1w0ltttf', name: '单证员'},
        ],
      },
      {
        id: '1eh77gn2',
        name: '其他采购/贸易职位',
        children: [{id: '47grkwud', name: '其他采购/贸易类职位'}],
      },
    ],
  },
  {
    id: '1mzh98ym',
    name: '供应链/物流',
    children: [
      {
        id: '4mfm3cw6',
        name: '物流',
        children: [
          {id: '8iq2loue', name: '物流'},
          {id: '2emtemey', name: '供应链专员'},
          {id: '3lwcv5is', name: '供应链经理'},
          {id: '21wzfzzy', name: '集装箱管理'},
          {id: 'ovjzf90e', name: '物流专员'},
          {id: '690l7xiu', name: '物流经理'},
          {id: '7emti04k', name: '物流运营'},
          {id: '1dw1u8ap', name: '物流跟单'},
          {id: '1ynusrcu', name: '调度员'},
          {id: 'lpimvobq', name: '物流/仓储项目经理'},
          {id: '1enp8jp1', name: '货运代理专员'},
          {id: '2dbfmfcc', name: '货运代理经理'},
          {id: 'h5velyva', name: '水/空/陆运操作'},
          {id: '9juttorb', name: '核销员'},
        ],
      },
      {
        id: 'e7kf4tek',
        name: '仓储',
        children: [
          {id: '4r3gpbt9', name: '仓储'},
          {id: '1hb2xp83', name: '仓库经理'},
          {id: '2ac1yhl2', name: '仓库管理员'},
          {id: '17j70lid', name: '仓库文员'},
          {id: '1zpoo6yr', name: '配/理/拣/发货'},
        ],
      },
      {
        id: '696omcly',
        name: '交通/运输',
        children: [
          {id: '2c597ozr', name: '交通/运输'},
          {id: '5jmrf260', name: '商务司机'},
          {id: '1mc64tt6', name: '网约车司机'},
          {id: '1go4011p', name: '代驾司机'},
          {id: '1770fdi0', name: '驾校教练'},
          {id: '715dsp56', name: '货运司机'},
          {id: '3lopn8rn', name: '配送员'},
          {id: '2mqm8j39', name: '快递员'},
          {id: 'cht668ze', name: '运输经理/主管'},
        ],
      },
      {
        id: 'djz18p6s',
        name: '高端供应链职位',
        children: [
          {id: '2l46v5ui', name: '高端供应链职位'},
          {id: '2gk61dsr', name: '供应链总监'},
          {id: '1lyb54g3', name: '物流总监'},
        ],
      },
      {
        id: '9gftcfbr',
        name: '其他供应链职位',
        children: [{id: '2lt7ixax', name: '其他供应链职位'}],
      },
    ],
  },
  {
    id: '2990l8ug',
    name: '房地产/建筑',
    children: [
      {
        id: '1m7miaio',
        name: '房地产规划开发',
        children: [
          {id: '2olkxmsu', name: '房地产规划开发'},
          {id: '1n7zi0fi', name: '房地产策划'},
          {id: '5w7qu8p4', name: '地产项目管理'},
          {id: '1e6afsye', name: '地产招投标'},
          {id: '28uri7g4', name: '房产评估师'},
        ],
      },
      {
        id: '2mwswhbb',
        name: '设计装修与市政建设',
        children: [
          {id: '23lbt49x', name: '设计装修与市政建设'},
          {id: '21kcsx0z', name: '建筑工程师'},
          {id: '28s1mv2z', name: '建筑设计师'},
          {id: '22sa3nn2', name: '土木/土建/结构工程师'},
          {id: '2gvjyucu', name: '室内设计'},
          {id: '1i9ha0yk', name: '园林/景观设计'},
          {id: '27a7b86o', name: '城市规划设计'},
          {id: '23298xvf', name: '工程监理'},
          {id: '23ip1oz6', name: '工程造价'},
          {id: 'ednjujma', name: '工程预算'},
          {id: '1newm2qx', name: '资料员'},
          {id: '1l9dke1m', name: '建筑施工现场管理'},
          {id: '160o9e6g', name: '弱电工程师'},
          {id: '1vfyjbjg', name: '给排水工程师'},
          {id: '2mlvqkf3', name: '暖通工程师'},
          {id: '5c8wfizr', name: '幕墙工程师'},
          {id: '2i4dw745', name: '软装设计师'},
          {id: '1e7t5otj', name: '施工员'},
          {id: '2jkyg4ty', name: '测绘/测量'},
          {id: '5uch9yci', name: '材料员'},
          {id: 'vkfs8rx9', name: 'BIM工程师'},
          {id: '1yvtkmwb', name: '装修项目经理'},
          {id: '1ce5rrwm', name: '建筑机电工程师'},
          {id: '1i5uxnm6', name: '消防工程师'},
          {id: '1yswpa54', name: '施工安全员'},
        ],
      },
      {
        id: '5j8n68bs',
        name: '物业管理',
        children: [
          {id: 'qsppuekn', name: '物业经理'},
          {id: '1ejjlw7t', name: '物业维修'},
          {id: '22ykldu4', name: '绿化工'},
          {id: '2fw7dulf', name: '物业管理员'},
        ],
      },
      {
        id: '1s2gqymj',
        name: '高端房地产职位',
        children: [
          {id: '2md7zwcz', name: '高端房地产职位'},
          {id: '20cx0gnz', name: '地产项目总监'},
          {id: '1gzi2jtq', name: '地产策划总监'},
          {id: '26unyu59', name: '地产招投标总监'},
        ],
      },
      {
        id: '26ok0ise',
        name: '其他房地产职位',
        children: [{id: '2cwu304f', name: '其他房地产职位'}],
      },
    ],
  },
  {
    id: 'kwabsc6v',
    name: '农/林/牧/渔',
    children: [
      {
        id: '19e6zdz6',
        name: '农业/林业',
        children: [{id: '1gtyvtq2', name: '农业/林业技术员'}],
      },
      {
        id: 'wm6h3udk',
        name: '畜牧/渔业',
        children: [
          {id: '1lggwqp7', name: '饲养员'},
          {id: '1dhakupp', name: '禽畜/水产养殖技术员'},
          {id: '9m2zili8', name: '畜牧兽医'},
        ],
      },
    ],
  },
  {
    id: '1mh47mcl',
    name: '咨询/翻译/法律',
    children: [
      {
        id: 'bczsd9vq',
        name: '咨询/调研',
        children: [
          {id: '1fcmdwnv', name: '咨询/调研'},
          {id: 'cm9r7b3h', name: '知识产权/专利/商标代理人'},
          {id: '2aqxzoyw', name: '心理咨询师'},
          {id: '2jc38xzo', name: '婚恋咨询师'},
          {id: 'bfd7zxwd', name: '企业管理咨询'},
          {id: '69z35ht2', name: '咨询总监'},
          {id: 'd21ey1m4', name: '数据分析师'},
          {id: '2bzxca7s', name: '咨询经理'},
          {id: '2my3qdny', name: '财务咨询顾问'},
          {id: 'zq6bs2tk', name: 'IT咨询顾问'},
          {id: '2adp2o9m', name: '人力资源咨询顾问'},
          {id: '1go3srm1', name: '咨询项目管理'},
          {id: '21fk893j', name: '战略咨询'},
          {id: '9x1p46zf', name: '猎头顾问'},
          {id: '1qkckbgm', name: '市场调研'},
          {id: '4i1fk79l', name: '其他咨询顾问'},
        ],
      },
      {
        id: 'a7nzk96s',
        name: '律师',
        children: [
          {id: '20tbgsjk', name: '专利律师'},
          {id: '1f62gj3a', name: '知识产权律师'},
          {id: '9mw5vusm', name: '律师助理'},
          {id: '1jt9jbsn', name: '事务所律师'},
          {id: 'c783l3zj', name: '法务'},
        ],
      },
      {
        id: 'b47u72fl',
        name: '翻译',
        children: [
          {id: '2as3x0p6', name: '英语翻译'},
          {id: 'v19y6zpo', name: '日语翻译'},
          {id: '247sgl7n', name: '韩语/朝鲜语翻译'},
          {id: '19i4tex0', name: '法语翻译'},
          {id: '1igjg1lm', name: '德语翻译'},
          {id: '2uh8i4rd', name: '俄语翻译'},
          {id: '3eoudmbw', name: '西班牙语翻译'},
          {id: '6vgog9oc', name: '其他语种翻译'},
        ],
      },
      {
        id: '55qdua52',
        name: '其他咨询类职位',
        children: [{id: '27uqpmn4', name: '其他咨询/翻译类职位'}],
      },
    ],
  },
  {
    id: '2p5o63wi',
    name: '旅游',
    children: [
      {
        id: '2dqvxtui',
        name: '旅游服务',
        children: [
          {id: '1xpmy9u9', name: '旅游服务'},
          {id: 'nwrau57i', name: '计调'},
          {id: '2e8mzd4b', name: '签证专员'},
          {id: '414101vv', name: '导游'},
          {id: '24v2qss6', name: '预定票务'},
          {id: '59niuocf', name: '讲解员'},
        ],
      },
      {
        id: '8iorufvx',
        name: '旅游产品开发/策划',
        children: [
          {id: '2jo1rfj9', name: '旅游产品开发/策划'},
          {id: '26h2tq9w', name: '旅游产品经理'},
          {id: '3fqoiobr', name: '旅游策划师'},
        ],
      },
      {
        id: '2llp7s1w',
        name: '其他旅游职位',
        children: [{id: 'xol4jxxq', name: '其他旅游职位'}],
      },
    ],
  },
  {
    id: '2k39clmv',
    name: '服务业',
    children: [
      {
        id: '2ejnwbbz',
        name: '餐饮',
        children: [
          {id: '1h44eaqx', name: '餐饮'},
          {id: '1svxnnv0', name: '后厨'},
          {id: '1nl7v1cr', name: '配菜打荷'},
          {id: '1wpfi0b3', name: '茶艺师'},
          {id: '2gxaer2v', name: '西点师'},
          {id: '1ybz725o', name: '餐饮学徒'},
          {id: '1zj1ypm8', name: '面点师'},
          {id: '2opmmsrr', name: '行政总厨'},
          {id: 'cjf2izc8', name: '厨师长'},
          {id: '5cisnom4', name: '传菜员'},
          {id: '2jecgz47', name: '洗碗工'},
          {id: '28l3x8yk', name: '凉菜厨师'},
          {id: '2jeorp4h', name: '中餐厨师'},
          {id: '1jvklr7t', name: '西餐厨师'},
          {id: '1041ugqu', name: '日料厨师'},
          {id: 'wdv7k1wh', name: '烧烤师傅'},
          {id: '17yfrqzq', name: '收银'},
          {id: '1rtewkmt', name: '服务员'},
          {id: 'fhbnz8lj', name: '厨师'},
          {id: '11d64tpp', name: '咖啡师'},
          {id: 'd6wfb89q', name: '送餐员'},
          {id: '19zcgqa8', name: '餐饮店长'},
          {id: '289gp63i', name: '领班'},
        ],
      },
      {
        id: '6dkciqrj',
        name: '酒店',
        children: [
          {id: 'vq9dicel', name: '礼仪/迎宾/接待'},
          {id: '2pjjl03r', name: '前厅经理'},
          {id: '192ddygq', name: '客房经理'},
          {id: '1ttvpg9i', name: '酒店前台'},
          {id: '26a130bi', name: '客房服务员'},
          {id: 'wkedey3w', name: '酒店经理'},
        ],
      },
      {
        id: '2y5st4yy',
        name: '零售',
        children: [
          {id: 'bl747tpk', name: '督导/巡店'},
          {id: 'bbxr6764', name: '陈列员'},
          {id: '2dieabv7', name: '理货员'},
          {id: '55wwkvlm', name: '防损员'},
          {id: 'b75ltuyz', name: '卖场经理'},
          {id: '1lo2q3q4', name: '促销员'},
          {id: '20930wbw', name: '导购'},
          {id: '19adt3t4', name: '店员/营业员'},
          {id: '6be3wbu4', name: '门店店长'},
        ],
      },
      {
        id: 'n7npxaj1',
        name: '美容保健',
        children: [
          {id: '228d7wrx', name: '纹绣师'},
          {id: '1k6k5zp2', name: '美体师'},
          {id: '26g56ypb', name: '美发学徒'},
          {id: '1phlj4ml', name: '美容店长'},
          {id: '2cz81b87', name: '足疗师'},
          {id: '11nn2arw', name: '按摩师'},
          {id: '2ccm6lg1', name: '美睫师'},
          {id: '612g4jgv', name: '发型师'},
          {id: '1w11idyu', name: '美甲师'},
          {id: '1v6s1iyl', name: '化妆师'},
          {id: '2aobnv4q', name: '养发师'},
          {id: '5w3yr2ag', name: '美容师'},
        ],
      },
      {
        id: '2eoxv2oi',
        name: '运动健身',
        children: [
          {id: 'akma3a2y', name: '健身'},
          {id: 'i8aw1d7g', name: '救生员'},
          {id: '27pbof6d', name: '瑜伽老师'},
          {id: '1rkl44dl', name: '游泳教练'},
          {id: '2m6wyc6a', name: '美体教练'},
          {id: '2i6l6mrs', name: '舞蹈老师'},
          {id: '19uk9v2z', name: '健身教练'},
        ],
      },
      {
        id: '2bjyezvo',
        name: '婚礼/花艺',
        children: [
          {id: '3td0dyso', name: '花艺师'},
          {id: '2kl6rmot', name: '婚礼策划'},
        ],
      },
      {
        id: '65u8e6ld',
        name: '宠物服务',
        children: [
          {id: 'filnzcgo', name: '宠物美容'},
          {id: '1g717x8e', name: '宠物医生'},
        ],
      },
      {
        id: '9ps5hw5a',
        name: '安保/家政/维修',
        children: [
          {id: '58g2xnbg', name: '保安'},
          {id: '2q3vkwiw', name: '保洁'},
          {id: '3rtdlirm', name: '保姆'},
          {id: '2hrbcgb4', name: '月嫂'},
          {id: '7nqabsf9', name: '育婴师'},
          {id: '79dplsyy', name: '护工'},
          {id: '2gfks7yd', name: '地铁安检'},
          {id: 'wt2u27uu', name: '手机维修'},
          {id: '7j3n2f25', name: '家电维修'},
          {id: 'pla962qm', name: '保安经理'},
          {id: 'vnvszud9', name: '产后康复师'},
          {id: '4yi502bj', name: '钟点工'},
          {id: '1pn21fkp', name: '押运员'},
          {id: '232eb2q4', name: '消防中控员'},
          {id: 'tm0f3jyg', name: '保洁经理'},
        ],
      },
      {
        id: '9y2f3716',
        name: '其他服务业职位',
        children: [{id: '2au9ys3n', name: '其他服务业职位'}],
      },
    ],
  },
  {
    id: '9nm7kgzb',
    name: '生产制造',
    children: [
      {
        id: '8wgzlnqf',
        name: '生产营运',
        children: [
          {id: '3vpxbhck', name: '生产营运'},
          {id: '1sxypdek', name: '厂长'},
          {id: '1yi2lucf', name: '生产总监'},
          {id: 'tsqy9e9c', name: '车间主任'},
          {id: '1wv4xbdz', name: '生产组长/拉长'},
          {id: '1e4ikqlu', name: '生产员'},
          {id: '2ew9xcc5', name: '生产设备管理'},
          {id: '2gotzxqn', name: '生产计划管理'},
          {id: 'il2fsuko', name: '生产跟单'},
        ],
      },
      {
        id: '24y1po5u',
        name: '质量安全',
        children: [
          {id: '5zqeuo0p', name: '质检员'},
          {id: '7k4onfb3', name: '质量管理/测试'},
          {id: '88ywgib1', name: '可靠度工程师'},
          {id: '1cjikiti', name: '故障分析师'},
          {id: '2ch7elup', name: '认证工程师'},
          {id: '626wkj8s', name: '体系工程师'},
          {id: 'd8gjpdvs', name: '审核员'},
          {id: 'txw39p6c', name: '生产安全员'},
          {id: 'rt3kpe4d', name: '汽车质量工程师'},
        ],
      },
      {
        id: 'hbsljlxk',
        name: '新能源',
        children: [
          {id: '1k177hjp', name: '电池工程师'},
          {id: '2fg59dez', name: '电机工程师'},
          {id: '63v3xrd6', name: '线束设计'},
          {id: '8yrd30zx', name: '充电桩设计'},
        ],
      },
      {
        id: '139llddd',
        name: '汽车制造',
        children: [
          {id: '6rqzd7r6', name: '汽车设计'},
          {id: 'qpu52j98', name: '车身/造型设计'},
          {id: '19fjdef4', name: '底盘工程师'},
          {id: '19e4xlin', name: '动力系统工程师'},
          {id: '204vder1', name: '汽车电子工程师'},
          {id: '2e3k310x', name: '汽车零部件设计'},
          {id: '248u1dj7', name: '汽车项目管理'},
          {id: '51dbvg57', name: '内外饰设计工程师'},
          {id: '1dxhu4ku', name: '总装工程师'},
        ],
      },
      {
        id: '1qzvdxux',
        name: '汽车服务',
        children: [
          {id: '29m2pfjd', name: '汽车服务顾问'},
          {id: '2akcdtg0', name: '汽车维修'},
          {id: '40u8wci0', name: '汽车美容'},
          {id: 'lq4q8sr0', name: '汽车定损理赔'},
          {id: '28rw047s', name: '二手车评估师'},
          {id: '27zk2edp', name: '4S店店长/维修站长'},
          {id: '1oos98f1', name: '汽车改装工程师'},
        ],
      },
      {
        id: '2pe56db6',
        name: '机械设计/制造',
        children: [
          {id: '9ba6ehkz', name: '机械设计/制造'},
          {id: 'c89ih03n', name: '热设计工程师'},
          {id: '2bj9dgo5', name: '精益工程师'},
          {id: '6yih8cxo', name: '机械工程师'},
          {id: 'nredzv72', name: '机械设计师'},
          {id: '219538u1', name: '机械设备工程师'},
          {id: '1wnfxnbm', name: '机械维修/保养'},
          {id: '14pr7d3f', name: '机械制图'},
          {id: 'dm58mgtc', name: '机械结构工程师'},
          {id: '155aos7t', name: '工业工程师'},
          {id: 'x6vgi4ty', name: '工艺/制程工程师'},
          {id: '1s0u88o0', name: '材料工程师'},
          {id: '2gy04duv', name: '机电工程师'},
          {id: '1fc7qso6', name: 'CNC/数控'},
          {id: '2o8rbgia', name: '冲压工程师'},
          {id: '24g9r7jp', name: '夹具工程师'},
          {id: '67jfo5er', name: '模具工程师'},
          {id: '1vkyrld0', name: '焊接工程师'},
          {id: '2cadym0o', name: '注塑工程师'},
          {id: '244ysp7m', name: '铸造/锻造工程师'},
        ],
      },
      {
        id: '25y1430n',
        name: '化工',
        children: [
          {id: 'xykokjil', name: '化工项目经理'},
          {id: '8g91oili', name: '化工工程师'},
          {id: '6vbvpo76', name: '实验室技术员'},
          {id: 'fqdabca7', name: '化学分析'},
          {id: '2l1vsphr', name: '涂料研发'},
          {id: '72j15enz', name: '化妆品研发'},
          {id: '1ltjxp38', name: '食品/饮料研发'},
        ],
      },
      {
        id: '1dlu78w9',
        name: '服装/纺织/皮革',
        children: [
          {id: '118y08hm', name: '服装/纺织设计'},
          {id: '5g7khg0g', name: '面料辅料开发'},
          {id: '9yt33lie', name: '打样/制版'},
          {id: 'dsqf2njd', name: '服装/纺织/皮革跟单'},
        ],
      },
      {
        id: '1azrrxik',
        name: '技工/普工',
        children: [
          {id: 'mssjwm6o', name: '普工/操作工'},
          {id: '8lrmet97', name: '挖掘机司机'},
          {id: '1y64iida', name: '叉车工'},
          {id: '2ca7kcfs', name: '铲车司机'},
          {id: '1qh1ectf', name: '焊工'},
          {id: '27yiqpqm', name: '氩弧焊工'},
          {id: '402jy7fi', name: '电工'},
          {id: '3dh9ic1r', name: '木工'},
          {id: 'aguclwou', name: '油漆工'},
          {id: '23wlfk9z', name: '车工'},
          {id: '2b1cecsa', name: '磨工'},
          {id: '1ezvo8x4', name: '铣工'},
          {id: '1t35xtep', name: '钳工'},
          {id: '1idp8hu8', name: '钻工'},
          {id: '5hxgx1l6', name: '铆工'},
          {id: '1ngs6ypb', name: '钣金工'},
          {id: '1c4ybpld', name: '抛光工'},
          {id: '2524c62v', name: '机修工'},
          {id: '26gbf554', name: '折弯工'},
          {id: '1ucp6mah', name: '电镀工'},
          {id: '22n27ot0', name: '喷塑工'},
          {id: '10mvcd8x', name: '注塑工'},
          {id: '2126s56g', name: '组装工'},
          {id: '16po9fhl', name: '包装工'},
          {id: '599wqits', name: '空调工'},
          {id: '13bof7ib', name: '电梯工'},
          {id: '1ea6ak0o', name: '锅炉工'},
          {id: '4ggw2icc', name: '学徒工'},
          {id: '1o9kvdx9', name: '缝纫工'},
          {id: '80gs2lod', name: '搬运工'},
          {id: '1pubwpbp', name: '切割工'},
          {id: '2134u3w7', name: '样衣工'},
          {id: '3y4uzs9n', name: '模具工'},
        ],
      },
      {
        id: 'zffkgxaz',
        name: '其他生产制造职位',
        children: [{id: 's00blowr', name: '其他生产制造职位'}],
      },
    ],
  },
  {
    id: '6crz72ig',
    name: '其他',
    children: [
      {
        id: '1lmfi6kp',
        name: '其他职位类别',
        children: [{id: '29yhcsfp', name: '其他职位'}],
      },
    ],
  },
];

export {useBossZhipinJobs};